CUDA_VISIBLE_DEVICES=0 python train_bi_affordance.py \
    --exp_suffix xxx \
    --log_dir ../logs \
    --model_version model_bi_affordance \
    --train_data_dir ../data/Train   \
    --val_data_dir ../data/Val     \
    --train_buffer_max_num 12000 \
    --val_buffer_max_num 1200    \
    --train_succ_proportion 0.5 \
    --train_fail1_proportion 0.15 \
    --train_fail2_proportion 0.15 \
    --train_fail3_proportion 0.15 \
    --train_fail4_proportion 0.05 \
    --batch_size 16  \
    --lr 0.001      \
    --lr_decay_every 500 \
    --lbd_kl 0.002     \
    --lbd_dir 1.0     \
    --lbd_critic 0.01   \
    --z_dim 32   \

