CUDA_VISIBLE_DEVICES=0 python train_disassembly_predictor.py \
    --exp_suffix xxx \
    --log_dir ../logs \
    --model_version model_disassembly \
    --train_data_dir ../data/Train   \
    --val_data_dir ../data/Val     \
    --train_buffer_max_num 7000 \
    --val_buffer_max_num 700    \
    --train_succ_proportion  1.0 \
    --train_fail1_proportion 0.0 \
    --train_fail2_proportion 0.0 \
    --train_fail3_proportion 0.0 \
    --train_fail4_proportion 0.0 \
    --batch_size 16  \
    --lr 0.001      \
    --lr_decay_every 500 \
    --lbd_kl 0.02     \
    --lbd_dir 5.0     \
    --lbd_rot 10.0    \
    --lbd_tran 1.0    \
    --z_dim 32   \

